# print("hellow i am list.py")
items = ["apple", "banana", "cherry"]
print(items) 
print(items[0])
print(items[1])
print(items[2])
print(items[-1])
print(items[-2])
print(items[-3])
items[0] = "grape"
print(items)
items.append("orange")
print(items)
items.insert(1, "kiwi")
print(items)
items.remove("banana")
print(items)
items.pop()
print(items)
